import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Video Note App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<div className={styles.center}>
					<Image
						className={styles.logo}
						src='/next.svg'
						alt='Next.js Logo'
						width={180}
						height={37}
						priority
					/>
					<div className={styles.thirteen}>
						<Image
							src='/thirteen.svg'
							alt='13'
							width={40}
							height={31}
							priority
						/>
					</div>
				</div>

				<div className={styles.grid}>
					<Link
						href='/signin'
						//href='#'
						className={styles.card}
						rel='noopener noreferrer'
					>
						<h2 className={inter.className}>
							SignIn <span>-&gt;</span>
						</h2>
					</Link>
					<Link
						href='/signup'
						className={styles.card}
						rel='noopener noreferrer'
					>
						<h2 className={inter.className}>
							SignUp <span>-&gt;</span>
						</h2>
					</Link>
				</div>
			</main>
		</>
	)
}
